### ISSUE TITLE
pyhon unittest fails with pyliblo3 on Fedora40

### ISSUE THREAD

**Issue by martinkg** [gesellkammer/pyliblo3#9]
Hi,

```
[martin@fc40 pyliblo3-91d17815b911ccc2c1d1408412e7885c32f2d460]$ /usr/bin/python3 -P -m unittest discover
E
======================================================================
ERROR: pyliblo3 (unittest.loader._FailedTest.pyliblo3)
----------------------------------------------------------------------
ImportError: Failed to import test module: pyliblo3
Traceback (most recent call last):
  File "/home/martin/rpmbuild/BUILD/pyliblo3-91d17815b911ccc2c1d1408412e7885c32f2d460/pyliblo3/__init__.py", line 19, in <module>
    from ._liblo3 import *
ModuleNotFoundError: No module named 'pyliblo3._liblo3'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib64/python3.12/unittest/loader.py", line 429, in _find_test_path
    package = self._get_module_from_name(name)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/unittest/loader.py", line 339, in _get_module_from_name
    __import__(name)
  File "/home/martin/rpmbuild/BUILD/pyliblo3-91d17815b911ccc2c1d1408412e7885c32f2d460/pyliblo3/__init__.py", line 21, in <module>
    raise ImportError("Failed to import the C extension module '_liblo'. Make sure it is compiled and available.") from e
ImportError: Failed to import the C extension module '_liblo'. Make sure it is compiled and available.


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
```
Regards
Martin

**Comment by martinkg** [comment]
the solution is:
$ rm -rf pyliblo3/_liblo.c
$ cython -I pyliblo3 pyliblo3/_liblo.pyx
